### ISSUE TITLE
3D Tiles Next - is it 3D Tiles 1.1 or 3D Tiles 2.0

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles#556]
3D Tiles Next introduces several draft 3D Tiles extensions and one glTF extension ([list](https://github.com/CesiumGS/3d-tiles/blob/main/next/README.md)) for implicit tiling, next-gen metadata, and better glTF integration.

Over the next 3-4 months, we will solidify the draft extensions and expand the software ecosystem, both via collaboration with the community, and then start the [OGC Community Standard](https://www.ogc.org/standards/community) process.

**3D Tiles Next** has been a codename (indeed, just like _glTF Next_ and _glTF PBR Next_).

Will this become
* 3D Tiles 2.0, or
* 3D Tiles 1.1, or
* Something else?

ISO versioning (semver like AFAIK) is not required so this is mainly a positioning question AFAIK.

On one hand 3D Tiles Next is a big leap with implicit tiling, metadata, and glTF improvements; on the other hand, things like more decoupled spatial subdivision (#555, #553), more decoupled metadata (#554), and vector tiles (#25) could follow quickly, and we may want to save the 2.0 splash for then.

We could also just wait, but I don't think we should increase the scope for the next OGC Community Standard iteration beyond the existing draft specifications.

**Comment by ptrgags** [comment]
As different as these new extensions are, 3D Tiles Next as it stands right now feels like 3D Tiles 1.1. The new features are all technically optional (since they are extensions). And from all these other discussion threads, larger architectural changes of 3D Tiles (especially in regards to integration with glTF, XMP and/or USD) are still on the horizon. I'd save the 2.0 version for then.

**Comment by lilleyse** [comment]
> ISO versioning (semver like AFAIK) is not required so this is mainly a positioning question AFAIK.

When we go to standardize 3D Tiles Next would we want to remove `b3dm`, `i3dm`, `pnts`, and `cpmt`? It's tempting because the spec will be much simpler centered around glTF.

I'm asking here because it could affect our decision for choosing 1.1 vs. 2.0.

[OGC Directive: 18 standard versioning](https://portal.ogc.org/public_ogc/directives/directives.php) says:

> A minor revision is backward compatible with previous versions with the same major version designation.

Do OGC directives apply to community standards? Even if not, a major version bump would feel warranted if we had a large breaking change like this.

**Comment by pjcozzi** [comment]
@lilleyse good points.  Also, if we deprecated `b3dm` and friends, we could also consider decoupling/removing/making-optional Declarative Styling as it is mostly used client-side AFAIK at runtime without transmission.

**Comment by lilleyse** [comment]
Say we went the 3D Tiles 1.1 route... would the current set of extensions be moved into the core spec or would they remain extensions? For the latter, would the version in tileset.json be 1.0 or 1.1?

**Comment by pjcozzi** [comment]
I _think_:

**1.1** = 1.0 + 3D Tiles Next extensions guaranteed available (and I guess not in the `extensions` for the 3D Tiles extensions, not for glTF ones).  `tileset.json` version would be `1.1`.

Just like new versions of OpenGL would bring OpenGL extensions into core.

Then there is still **1.0** + 3D Tiles Next extensions.  `tileset.json` version would be `1.0`

Perhaps worth a few minutes to compare this to what happened with glTF 1.0 + extensions -> glTF 2.0 to confirm that this is aligned.

**Comment by javagl** [comment]
It is 3D Tiles 1.1.
