### ISSUE TITLE
Alternative to `type` and `componentType`

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#595]
This is a proposed alternative to how types are defined in the 3D Metadata spec, inspired by [basic datatypes in USD](https://graphics.pixar.com/usd/docs/api/_usd__page__datatypes.html).

# Proposed

### Basic types 

`u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `u64`, `i64`, `f32`, `f64`, `string`, `bool`, `enum`

### Vector types

Just add vec2, vec3, vec4 to the end of a numeric type

**Examples**: `u8vec3`, `f32vec4`

### Matrix types

Just add mat2, mat3, mat4 to the end of a numeric type

**Examples**: `f32mat4`, `f64mat3`

### Array types

Just add `[]` or `[n]` to the end of the type. `[]` represents variable-size arrays, `[n]` represents fixed-size arrays.

**Examples**: `string[]`, `bool[10]`, `u8vec3[4]`

## So what are the benefits of this?

* Better conceptual separation of basic types and arrays. This is a useful separation at the glTF level as well.
* Supports arrays of vectors and matrices
* Only a single `type` need
* Types are still familiar looking - some mix of [rust types](https://doc.rust-lang.org/book/ch03-02-data-types.html) and glm
* Opens up possibility of more complex types (e.g. RGB565)

Downsides:

* Types are now represented as strings rather than enums and require light regex parsing on the client
* Conceptually different than glTF

**Comment by lilleyse** [comment]
<table>
<tr>
<td>Current&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>Proposed&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
</tr>
<tr>
<td>

```json
"property": {
  "componentType": "STRING"
}
```

</td>
<td>

```json
"property": {
  "type": "string"
}
```

</td>
</tr>
</table>

<table>
<tr>
<td>Current&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>Proposed&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
</tr>
<tr>
<td>

```json
"property": {
  "componentType": "FLOAT64"
}
```

</td>
<td>

```json
"property": {
  "type": "f64"
}
```

</td>
</tr>
</table>

<table>
<tr>
<td>Current&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>Proposed</td>
</tr>
<tr>
<td>

```json
"property": {
  "type": "ARRAY",
  "componentType": "STRING",
  "componentCount": 10
}
```

</td>
<td>

```json
"property": {
  "type": "string[10]"
}
```

</td>
</tr>
</table>

<table>
<tr>
<td>Current&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>Proposed&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
</tr>
<tr>
<td>

```json
"property": {
  "type": "VEC3",
  "componentType": "UINT8"
}
```

</td>
<td>

```json
"property": {
  "type": "u8vec3"
}
```

</td>
</tr>
</table>


<table>
<tr>
<td>Current&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>Proposed&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
</tr>
<tr>
<td>

```json
"property": {
  "type": "ARRAY",
  "componentType": "BOOLEAN"
}
```

</td>
<td>

```json
"property": {
  "type": "bool[]"
}
```

</td>
</tr>
</table>

**Comment by javagl** [comment]
This is a bit of brainstorming....

When considering this as an alternative to the current way of defining types, I try to think about some "dimensions":

- How easily can the input (as JSON) be processed by the client?
- (Independent of that: ) How will the actual structural information be _used_ by the client? 

One could say: "In the end, it does not matter", because the actual information that is conveyed should be the same. The comparison in the previous post already shows, to some extent, that these are just different forms to describe the same, abstract idea - namely, the actual type information.  

---

Zooming one level deeper:  

- What is the _expressiveness_ of the approaches?
- (Somewhat related to that:) What _should_ be expressable? 

One could plainly ask: Is there something that can be represented with one approach, but **not** with the other? But the related question is: What _should_ be possible? 

- The example of "arrays of vectors" was already given: It is possible with the "new" approach, but not with the "old" one 
- Should an "array of arrays" be representable?
- Should a "3D vector of strings" be representable?
- ...

In any case, there may be constraints that are put _on top_ of the actual, textual representation - meaning that these types can be _represented_, but should not be _allowed_.

One crucial difference in the expressiveness is: With the new approach, these things _could_ be made valid easily. With the old approach, an array of arrays (even just a 2D array as an alternative for a matrix) will _never_ be possible, because saying `componentType : ARRAY` does not fly. In the new approach, one could simply say: "Yeah, append another `[]` there: `f32[][]`". 

---

This leads to another level (a somewhat _higher_ one this time) :

- How (easily) extensible are the approaches?

The extensibility may be analyzed in view of different questions:

- In how far can the "basic types" be changed?
- In how far can the "structure" be changed?

For example, if someone wanted to add a 16-bit-float value type - usually called 'half precision' - then one could do this easily in both approaches, by adding `f16` as the `componentType` or one of the "Basic Types". Allowing a "3D vector of strings" would also be possible. But as mentioned above: Things like a 3D array cannot be represented with the old approach. (The point that the new approach allows "arrays of vectors" was already mentioned as one of the benefits of the new approach).

---

When it comes to extensibility, one of the first questions becomes relevant again: 

- How will the actual structural information be _used_ by the client? 

This refers to the _implementation level_ this time. Programming languages vary wildly in their type systems. For example, there are untyped langauges, and <strike>proper</strike> typed ones, and can can ask whether these property types can be represented sensibly in the respective type system.

For example: In JavaScript, one might use a `Float32Array` for an "array of floats", but _also_ for an array of "3D vectors of floats" - simply because there is no other sensible way to represent the latter. In C++, one might conveniently use a `std::vector<glm::vec3>` here. Getting to the bottom of this is nearly impossible. (E.g. at some point, one would have to ask  whether `f32vec3` and `f32[3]` can be converted into one another by casting...)

Another aspect of extensibility is: **If** the system is changed (e.g. by allowing a `f16` type, or by allowing 2D arrays), then **where** is this change encoded, and **how** do dlients have to react to that change? A client might already have some pseudocode
```
enum BasicType {
    u8, i8, .... f64;
}

BasicType basicType = getTypeFrom(property); 
switch (basicType) { ... }
```
Adding an `f16` type there is trivial: The enum is extended, and the `getTypeFrom` method is updated (and it doesn't matter whether this is the "old" or "new" approach!). For "structural" changes, things might become more complicated.

---

As an aside:

> * Types are now represented as strings rather than enums and require light regex parsing on the client

Whether or not the client uses regex does not matter. The "grammar" could/should be defined, and then the client can either build a RegEx, dissect the strings manually, or just throw the grammar into ANTLR or yacc or whatever. 

Here's a _sketch(!)_ of what this could look like as EBNF:

```
(* Basic types, differentiated between numeric and non-numeric *)
basicNumericType = "u8" | "i8" | "u16" | "i16" | "u32" | "i32" | "u64" | "i64" | "f32" | "f64";
basicNonNumericType = "string" | "bool" | "enum";
basicType = basicNumericType | basicNonNumericType;

(* Vector and matrix types, defined only on the numeric base types *)
vectorType = basicNumericType | [ "vec2" | "vec3" | "vec4" ];
matrixType = basicNumericType | [ "mat2" | "mat3" | "mat4" ];

(* Natural numbers for the array sizes *)
nonzeroDigit = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
digit = "0" | nonzeroDigit;
naturalNumber = nonzeroDigit, { digit };

(* Array types are all types with appended brackets and an optional size *)
arrayIndicator = [ "[]" | "[", naturalNumber, "]" ];
arrayType = [ basicType | vectorType | matrixType ], arrayIndicator;

(* The actual definition of the types, in all forms that it may have *)
type = [ basicType | vectorType | matrixType | arrayType ];
```

**Comment by donmccurdy** [comment]
> One could say: "In the end, it does not matter", because the actual information that is conveyed should be the same.

Mostly agreed, but with an addition — given two syntax options that are otherwise equivalent, we might prefer one that is more consistent with other parts of 3D Tiles, glTF, or another relevant standard.

***

>  What is the expressiveness of the approaches? ... What should be expressible?
> ...
> How (easily) extensible are the approaches?

The possibility of more complex types (e.g. `float32[2][2][2]`) is interesting, although the new proposal is also constrained by syntax in its own particular ways. Mixed types like `[string, uint8, uint8]` cannot be expressed. Custom structs ([present in Apache Arrow](https://arrow.apache.org/docs/python/data.html#struct-arrays)) are not possible. It is always possible to get incrementally more flexibility in exchange for incrementally more complexity – the difficulty in standards is knowing where to draw the line. 😩

We might be at the point where it's necessary to first decide which data types are within scope, either currently or within the foreseeable future. Ideally (and fortunately true here) there are other standards and libraries we can compare. We don't need the full complexity of XMP or RDF descriptions, but libraries and formats for transmission- or analysis-ready columnar data would be relevant. 

Perhaps with some exceptions for formats relevant to GPU APIs (e.g. half float), I think it's probably safe to claim that data types not broadly present in modern data science libraries and formats can be ruled out. For comparison:

- [Apache Arrow Data Types](https://arrow.apache.org/docs/python/api/datatypes.html)
- [Python DataFrame dtypes](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes)
- [R Data Types](https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/)
- [TileDB Datatypes](https://docs.tiledb.com/prestodb/supported-datatypes) _*(notably lacking compound types, unless I've missed something?)_

Based on those we probably don't need to worry about N-dimensional arrays, but there are several other examples that would require more flexibility than our `componentType` and `type` properties. Parameterized types like Arrow's `time32(unit)`, `time64(unit)`, and `timestamp(unit[, tz])` — or Python's `datetime64[ns, <tz>]` — could be worth considering.

**Comment by javagl** [comment]
I'll try to roughly summarize some of the dimensions that recent discussions of the type system revolved about.

---


### The distinction between `type` and `componentType`:

The `type` usually referred to types with fixed, predefined structures (like a `vec3` or `mat4`. 

The `componentType` referred to "single values", or the componenty of these structure types (e.g. `float32` or `uint16`).

For the `type`, there was the question of whether `array` should be part of these.

For the `componentType`, one question was whether `string` and `enum` should be part of these.



### Modeling arrays

The distinction here is between three different things:

- Whether something is an array at all
- Whether something is a fixed-length array
- Whether something is a dynamic-length array



### The representation in the schema

This mainly refers to whether the schema should be written with separate fields, as in `{ type: vec3, componentType: float32 }`, or whether all type information should be encoded in a string, as in `type: vec3float32`. (I'll consider that as a detail for now - as mentioned in earlier: The different representations _might_ be equivalent in many ways).



### Special types and types that may have to be added

There have been considerations to add various types, and discussion about how these types could be added

- Some sort of `timestamp` type. This could be a string in ISO 8601 format ... or one of a bazillion other formats. The generalization would be: Types that are represented as strings, and where their validity may (to some extent) be checked with a RegEx. 
- Special (single) types, like `RGB565`, which is a 16 bit encoding or RBG colors, or even something like `latitude`, which is just a `float` with a certain "semantic"...
- Certain (fixed) structured types, like a `quaternion`...



### Custom structured types

One open question is whether (or how) custom structured types should be supported (in contrast to the fixed, predefined structures like `vec3` or `mat2`, or `quaternion` in the future) - for example, whether it should be possible to define `MyCarConfiguration { float speed, Color color }, MyColor { float r,g,b }`. 



### The encoding of enums or booleans

Right now, in the JSON version, enum values are encoded using the string, like `"enumValueA"`. One could make a case for encoding these values directly as an integer value. (How to define whether it is a `UINT8` or a `UINT32` has to be discussed). 

Similarly, one could consider special encodings for booleans. For example, it would be nice to have a mechanism that allowed defining that a `boolean[8]` is actually stored as a single byte in its binary representation (e.g. to encode things like the availability bitstreams from implicit tiling - this would then be a `boolean[8][numNodes]` ~ `uint8[numNodes]`)


---


Inspiration about "How To Model Types" can be found in various places. For example, the ones that Don already linked to:

- Apache Arrow Data Types
- Python DataFrame dtypes
- R Data Types
- TileDB Datatypes 

The latter is only one of many databases, and one could look at others as well (e.g. SQL). 

Further ways of defining types could be

- [Google Protocol Buffers](https://developers.google.com/protocol-buffers/docs/proto3#scalar)
- [LLVM type system](https://llvm.org/docs/LangRef.html#first-class-types)
- ...
- Literally every programming language (unless they took the "easy" path of an untyped language...)

And just to mention that for completeness: The current solution, with `type` and `componentType`, is very similar to glTF in many ways.

---


The following is an update of the [brainstorming in my previous post](https://github.com/CesiumGS/3d-tiles/issues/595#issuecomment-982756021), updated with some thoughts from the recent discussion:

Consider a set of four 32-bit floating point values. These values could reasonably be

- A `float32[4]` array
- A `vec4<float32>`
- A `mat2<float32>`
- A `quaternion<float32>` (in the future)
- A `rectangle<float32>` (in the future)
- ...

I talked about "four 32-bit floating point values", and everybody knew what it was. I wrote down the possible types, and everybody knew what they meant. In that manner, I think that there are two purposes for the type definitions in our context:

- Defining an _encoding_ of data
- Defining a _meaning_ of data

Defining the encoding of four 32 bit floating point values could be simple:

`float32[4]`

Everything else is put on top of that. 

(I know, there **are** subtle details. For example, if this is supposed to be a `mat2`, then there has to be information on whether the matrix is stored in row- or column major order. If it is supposed to be a `rectangle`, then it would be `x0,y0,x1,y1`, or `x,y,w,h`. Even for a `quaternion`, it is not obvious which of the component describes the "scalar" (angle) part...)

---

Some highly subjective points, derived from the discussion:

- There should be a predefined, **fixed** set of basic ("primitive") types. These should not be associated with any meaning. They should only describe "the size", in terms of number of bits. This roughly corresponds to the `componentType`. Whether or not `string`, `boolean` and `enum` should be part of these types has to be decided. If they are included, then there should probably be an _explicit_ distinction between numeric- and non-numeric component types, so that it is possible to cleanly define that `vec3<numericType>` is valid, but `vec3<string>` is not valid (see the EBNF grammar at the bottom of my previous post).

- The concept of a "array" should be totally orthagonal to all other type information. Right now, one limitation of the type system is that it is not possible to have an "array of vectors", because `ARRAY` and `VEC3` are both listed as one `type`.
  - Regarding the _size_ of arrays: There had been considerations to remove `ARRAY` from the `type`, and model the _array-ness_ of a property solely with the `componentCount` field. (And although I don't like the introduction of "special values", like `-1` meaning "variable length", that could be OK, because it still can be defined cleanly and unambiguously). But what I'd consider to be more important: A single `componentCount` does not work for multidimensional arrays. I'd prefer an alternative that allows modeling multidimensional arrays (regardless of whether they are allowed in the first iteration). This could be encoded in different ways. The obvious one could be to have something like a field `arraySize: [ 3, 4 ]` for a 2D array, or `arraySize: [5, 6, -1]` for a 3D array where the last dimension has variable length (iff this should be allowed...). Alternatives could be strings, like `arraySize: "[5][6][-1]"`, to convey the same information - that's a detail for now. 
  
- It does not make sense to try and list all "structured" types that may be required in the future in the schema. Right now, we have `vec4` and `mat2`, both describing "four values". In the future, there could be `quaternion` `rectangle`, or maybe `boundingSphereWithCenterAndRadius`, and that set would potentially be _infinite_. I don't see a way of how that set could be sensibly defined, and even less maintained. 
  (Of course, I **do** see the reasoning behind fixed, structured types: `matX` and `vecX` are so important and prominent for graphics that one can make a case for giving them _a name_. But ... only for `X=2,3,4`, and there are infinitely many things that _could_ make sense...)
  
- In view of the differentiation between _encoding_ data and defining the _meaning_ of data, I think that it could make sense to have something that lies between the basic type system, and the [Semantics](https://github.com/CesiumGS/3d-tiles/tree/main/specification/Metadata/Semantics) that we already have. This could be something that provides the actual information of whether "four 32 bit floating point values" actually **are** a `mat4`, or a `quaternion (x,y,z,angle)`, or a `quaternion (angle,x,y,z)`.... 

---

(I started scribbling a few more thoughts and examples what this _might_ eventually look like. But it's very different from the existing approaches, and may raise questions in terms of implementation complexity. So I'll leave it at that for now...)

**Comment by lilleyse** [comment]
@javagl I'd be really curious to see some examples even if they're different than existing approaches. I find myself agreeing with all your points.

**Comment by javagl** [comment]
I'll try to extend this, but with a huge disclaimer: It's still brainstorming, not a proposal, and I'll point out some caveats here. 

- The fixed set of basic numeric types, roughly corresponding to the current `componentType`
  - "u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64", "f32", "f64" (or the long forms, like "float32")

- The fixed set of basic non-numeric types
  - "string", "bool", "enum"
  
- Whether something is an array is indicated by a value, roughly as in our `componentCount`:
  - a size of -1/0/n for dynamic size, single values, or arrays of size `n`, respectively
  - (It is not possible to explicitly model an array of size 0. We could think about that...)
  
As mentioned earlier, the way how this information is represented in the schema (i.e. with properties like `arraySize:4`, or as part of a string as in `"float32[4]"`) has to be discussed. I'm subsequently using the string-based form, because it's easier to write it down (at the cost of being much harder to parse/process in the implementation...).  

The "structured" types could be modeled as classes. And this could be done for **all** the structured types. This means that there would not be predefined types like `vec4` in _the type system itself_. 

#### Modeling structured types

There could be different representations for the structured types. For example:
```
"classes": {
  "vec4": {
    "description": "A simple 4D vector",
    "properties": {
      "x": { "float32" },
      "y": { "float32" },
      "z": { "float32" },
      "w": { "float32" }
    }
  }
}
```
But it could also be modeled like this:
```
"classes": {
  "vec4": {
    "description": "A simple 4D vector",
    "properties": {
      "components": { "float32[4]" }
    }
  }
}
```
And this would be equivalent. Both representations define the 4D vector to be a sequence of 4 consecutive (tightly packed) `float32` values. Depending on the programming language and library, this could be used to create an instance of a 
```
struct Vec4 { float x,y,z,w; }
```
or a plain
```
float v[4];
```
array (and in C, it could even be casted brutally, as in `Vec4 *v = (Vec4*)(&array[0];` - don't try this at home), or it could be read into a 
```
Cesium.Cartesian4.fromArray(fourFloats, 0);
```
The definition of the _structure_ of the structured type can (and IMHO should) _not_ dictate that this exact type has to be present and be used in the targeted programming environment. 

Modeling types like a `quaternionA { x,y,z, angle }` and `quaternionB { angle, x,y,z }` would be simple. Compound types like `boundingBox { vec3 min; vec3 max; }` would also be simple. 

But an obvious caveat: I said that a `vec4` is a sequence of 4 `float32` values, but this does not cover the other component types. This could, roughly speaking, be addressed in two ways:

- Listing all parameterizations. There could be such a schema for vector types that explicitly lists them, as in `vec3_uint8`, ... `vec3_int16`, ... `vec3_float32`. This is ugly, because it is redundant, causes a combinatorial explosion, and is not easily extensible. (The latter refers to something like a `float16` being added later. This is one reason why these basic types should be _stable_, but still has to be kept in mind)
- Allowing arbitrary parametrizations. For example, one could allow a `vec4<T>` as
  ```
  "classes": {
    "vec4<T>": {
      "properties": {
        "x": { "T" },
        "y": { "T" },
        "z": { "T" },
        "w": { "T" }
      }
    }
  }
  ```
  and then refer to this as `vec3<float32>`. This could impose a considerable burden on implementors. And this does not even yet mention possible constraints on these parameters, like "`T` must be a _numeric_ type" ... 

Maybe there is some in-between solution with the best of both worlds. Maybe the `class` above could be called `classTemplate`, and the _specific_ classes from the schema could be specific instantiations, something like `"vec4_float32" { "template: ..., "T": "float32" }`, but ... at _this_ point, it's obviously not simple any more: Implementors would eventually have to implement something that is similar to what has to be done for programming languages, in terms of genericity and expressiveness.


#### Managing structured types

Regardless of how _individual_ structured types are _modeled_, there is still the question of how multiple structured types are _managed_. 
If structured types are not part of the "core" type system, but always defined in a schema as a `class`, then some of the common types (`vec3` et al) have to be defined _somewhere_. And they could be managed by <strike>simply</strike> defining this as an external schema.

For example, consider a structure like this:
```
"3DTILES_metadata": {

  // The imported part, which is a schema that defines "3D vectors"
  "schemaUris": [
    "https://cesium.com/metadata/1.0/vectorTypes.json"
  }
  
  // The custom part, with a building where the "bounds"
  // are given by a 3D float vector:
  "schema": {
    "classes": {
      "building": {  
        "bounds": { "type": "vec3<float32>" }
      }
    }
  }
}
```

One could imagine that the `schemaUris` refer to one or multiple other schemas. There could be dedicated schemas for `vectorTypes`, `matrixTypes`, `colorTypes`, `timestampTypes` etc. This could allow a clean separation of type definitions, and allow some "import what you use" mentality. Instead of clobbering "our" (core) type system with 42 different representations of a "timestamp", we'd collect them in one schema, and allow the user to either use them or not - or define own ones, if necessary.

Of course, this raises several questions in terms of schema composition: 

- Where are the schema files stored or hosted? 
- How to handle ambiguities? (We could say that custom types have to be prefixes with an `"_"` underscore or so, but that wouldn't solve all problems in the long run. Some sort of "namespaces" could do it, but with more complexity)
- (Still: How to refer to the type? I used `vec3<float32>` above, but maybe it should be `vec3_float32` instead)

---

I think that _some_ of these ideas have obvious benefits. Having a clean "core" type system with the basic types, and on top of that a _mechanism_ for defining structured types (and "libraries/schemas" of prefefined structured types) could offer flexbility, stability, genericity, composability, and extensibility. You want a set of bounding volume types? Go on, define your `boundingVolumeTypes.json` schema with `boundingBoxMinMax`, `boundingBoxCenterHalfAxes`, `boundingSphereCenterRadius`, `boundingSphereRadiusCenter` or whatever you desire. If you want to use S2 bounding volumes on top of that, just add another `schemaUri : "s2BoundingVolumes.json"` to your metadata. 

**But** ... as mentioned inlined: All this raises some questions that are hard to answer. Specifically: There sometimes are "simple" answers that create "ugly" results, and when trying to achieve "nice" results, then the answers are not "simple" any more, and could impose a burden on the implementor side that could be hard to justify. So again: All this is brainstorming. But maybe some positive aspects or ideas can be derived from that in a further discussion, finding the right balance between genericity and implementation effort.

**Comment by ptrgags** [comment]
I agree with the following points:
* keeping arrays separate from the types contained within
* Making a distinction between the storage type e.g. `float[4]`, the interpretation e.g. `quaternion (x, y, z, angle)`, and the semantics e.g. `ROTATION`. Though not sure the best way to encode it

Points I'm on the fence about:
* multidimensional arrays. do we have a strong enough use case for them?
  * if so, look at Python's [NumPy library](https://numpy.org/doc/stable/index.html) for examples. they use a `shape` tuple (like the `arraySize` proposed above.  As far as I'm aware, NumPy optimized for arrays of fixed size, so maybe we could disallow variable-length multidimensional arrays
* should vectors and matrices be built-in types since they're very common 3D types? even if quaternions and other things are not. 

Some parts I'm not quite happy with:
* I don't like the idea of requiring an EBNF grammar to parse the types. That's significant complexity for the implementer. Right now, we don't even have to resort to regex parsing. Keeping things easy to parse I think is important.
* Using classes for structured types (like `vec4`) seems like a misuse of the class concept. Classes are intended to describe the columns of a property table, where here it's being used to describe structure for a single column. I think a separate struct concept would be better.

Maybe we want an ability to make type definitions? here's one possibility:

```jsonc
"typedefs": {
  // I still think for matrix/vector (_possibly_ quaternions) we should have built-in types for these since they're so common in graphics.
  "mat2": {
     "alias": "float32[4]",
     // column-major matrix
     "interpretation": "MATRIX"
  },
  "vec3": {
     // ordered array so packing in binary is unambiguous
     "properties": [
        {"name": "x", "type": "float32"},
        {"name": "y", "type": "float32"},
        {"name": "z", "type": "float32"},
     ]
  },
  "rectangle": {
    "properties": [
        {"name": "west", "type": "float64"},
        {"name": "south", "type": "float64"},
        {"name": "east", "type": "float64"},
        {"name": "north", "type": "float64"},
        {"name": "minimumHeight", "type": "float64"},
        {"name": "maximumHeight", "type": "float64"},
     ]
  },
  "sphere": {
      "properties": [
        // dangerous territory - do we allow recursive type definitions?
        // of course if vec3 was a built-in type this particular case would be fine.
        {"name": "center", "type": "vec3"}, // might be easier to parse if we make the type "typedef:vec3"?
        {"name": "radius", "type": "float64"}
      ]
  }
},
"classes": {
  "exampleClass": {
    "properties": {
      "name": {"type": "string", "semantic": "NAME"},
      "boundingSphere": { "type": "typedef:sphere"},
      "boundingRectangle": {"type": "typedef:rectangle"}
    }
  }
}
```

**Comment by lilleyse** [comment]
I think it's totally fine to model structured types as classes since classes are a logical concept that is distinct from the physical encoding.

For example, a `vec3` class: I don't know how the data is stored but I know I can access the x component by writing `property.x` in a custom shader or style.

So between the two representations that @javagl posted, I much prefer the first one.

```
"vec3": {
  "properties": {
    "x": { "type": "float32" },
    "y": { "type": "float32" },
    "z": { "type": "float32" }
  }
}
```

It would be the spec's job to define all the structured types and their encodings. The encoding for `vec3` would be something like:

```
An array of three numbers ordered as [x, y, z]
```

I think that's all that's needed to get this system working. Everything is a class (except the basic types) and structured types are classes with special "meta" encoding rules. I don't think the structured types can or should be defined in a schema file, instead they would have to be built-in types.

I'm not completely sure what to do about templated types, but I'm not against listing all parameterizations even if there are a couple hundred. I'm also ok with the template approach @javagl posted, or a `type`/`componentType` system like glTF. Probably leaning the most towards the latter.

**Comment by lilleyse** [comment]
Multi-dimensional arrays can be supported indirectly if we allow classes to have properties that are other classes, which goes beyond the scope of this issue but could be done.

**Comment by javagl** [comment]
@ptrgags 

> should vectors and matrices be built-in types since they're very common 3D types? even if quaternions and other things are not. 

I agree that vectors and matrices play a special role. But the same could be said for quaternions. And depending on the context, even for things like a rectangle or bounding box. The main reasoning for me to carve matrix+vector out of the "core" type system was that it's impossible to draw a line here. A middle ground could, _very_ roughly speaking, be to declare these types as "implicitly defined". So that it's not necessary to do some `imprtSchema : [ myVecTypes.json ]` to have them available, but just saying that they are available by default, _as-if_ one had imported a such a schema file. But that's still a bit muddy...

> I don't like the idea of requiring an EBNF grammar to parse the types. 

Just to clarify: That was not part of the proposal, and I agree that "keeping things simple" is important. Whether or not it is necessary to define (or use) a grammar depends on the complexity of the types that should be possible. 


> I think a separate struct concept would be better.

It's not entirely clear in how far that would go beyond replacing `"class"` with `"struct"`, but will think about that more thoroughly.

> `// dangerous territory - do we allow recursive type definitions?`

If "recursive" meant "types that refer to other types on the same level", I'd say "yes". If "recursive" referred to something like `cloass LinkedListNode { LinkedListNode next; }`, then I'd say "no".


---

@lilleyse  

> I don't know how the data is stored but I know I can access the x component by writing property.x in a custom shader or style.

Whether or not a client can access a property like this depends on the type that the client used to deserialize that instance. The type in the schema could be a `class Vec3 { float32 x,y,z; }`, but the client could reasonably store this data in a `float32[3]` if he wanted to.

**Comment by lilleyse** [comment]
As an intermediate step it might be worth agreeing on how arrays should be handled, since I think we all agree that they should be handled differently. Here's one approach that isn't significantly different than what we have now.

**type**

SCALAR, VEC2, VEC3, VEC4, MAT2, MAT3, MAT4, STRING, BOOLEAN, ENUM

**componentType**

INT8, UINT8, INT16, UINT16, INT32, UINT32, INT64, UINT64, FLOAT32, FLOAT64

`componentType` is only applicable to scalars, vectors, matrices, and other built-in templated types, which in the future could include quaternions and colors.

**How to handle array count**

I don't really like the -1 sentinel. What if we had two mutually exclusive properties, `count` and `variableCount`

##### Fixed size array
* `"count": 10`

##### Variable size array
* `"variableCount": true`

##### Single element
* Nothing specified

**Comment by javagl** [comment]
Instead of `variableCount` (defaulting to `false`), the field is currently called `hasFixedCount` (defaulting to `true`)

**Comment by lilleyse** [comment]
For the array representation we've settled on 

```
// Fixed length
array: true
count: 2
```

```
// Variable length
array: true
```

**Comment by lilleyse** [comment]
Closing for now :crossed_fingers:
