### ISSUE TITLE
Accessing point attributes for dynamic re-coloring (declarative styling)

### ISSUE THREAD

**Issue by JordanMakesMaps** [CesiumGS/3d-tiles#603]
I'm interested in doing declarative styling so that we can manipulate the color of individual points within a point cloud (i.e., 3D tileset). 

Currently my process involves converting existing file formats into a .laz file and then uploading to Cesium via REST API. When using one of the Sand Castle examples I see how specific variables (height, temperature, etc.,) can be accessed, and through conditional logic their color or "style" can be altered on the front-end. However, when trying the same example with our own assets I'm unable to access these variables (likely because we did not set them).

My question is, at what point in the uploading, tiling, and viewing pipeline do I need  to provide the necessary information to the Point Cloud asset so that I can perform declarative style?

**Comment by lilleyse** [comment]
@JordanMakesMaps what properties does your point cloud have? If your points have color it will be available as the `${COLOR}` built-in property. If they have classification or intensity it will be available as `${Classification}` and `${Intensity}`.

Hopefully this helps. If you have other questions feel free to open an issue in the Cesium community forum: https://community.cesium.com/.

**Comment by JordanMakesMaps** [comment]
@lilleyse thanks, I see that now. With regards to {POSTION}, are the attributes (.x, .y, z.) in the same format as they were before uploading? I'm uploading .laz files that have negative values Z-values, but in the {POSITION}.z doesn't seem to reflect that.

Thanks.

**Comment by lilleyse** [comment]
`${POSTION}` is the cartesian position as stored in the tile, and not the original position since there are a series of coordinate transforms that happen in-between. The original positions would need to be stored in the tile separately which ion doesn't support right now.

While it's not exactly what you're looking for, you can style based on ellipsoid elevation by using `${POSITION_ABSOLUTE}` like in [this sandcastle](https://sandcastle.cesium.com/#c=tVdrb9s2FP0rhFegMmbLevmh1AnWeq8A3VLMbvdhHgpKom0iEimQlF0v8H/fJSk5cpygXdcECWxe8t5z7pPMFgu0pWRHBLpEjOzQjEhaFe4HI3OWndSsZ5wpTBkRy04P3S0ZQooIAZJ3gm9pRsRFo5gKghX5k4s8W9gjTre3ZIfuqyVbsi3AKZoTSRTgWWBXpoQRtxS0oIpuiXRxljkao8XHfoQ/LqyyYzggVIn8iHzN2R9E8kqkxF0JXryWcPA6c4JJHA01B61QcsrULOdVNt/gjLL1BapNIYSVIqzCinJ2gZSoSK/ZKfAnWlTF6/aBoN49mM9Dd8msi7V7LsQh20N4CiqJqzaEOauKpVrX6VrMwQDN1T4nKMGSZIgztCF0vVFIs0ckz2kpOc3qo4sNlQh+MUO4LAUHRoYJCDK0wbCBVhCvUpCUSi1P8RZSIWt1hHwXbBC0qgSwEQjv8B50TEC0XQMKO8f8QFYgycihTCe7kIivUM7ZmqoqIz2UA7r+1jVKBRcEUcZwWgnIv5HV3iQk5QW55xG46N3N/HpxffP7x9dv5jdv3y9+Mo6hMOgnVKEtzittzBiRkCZgsdvQdKNPMa6QrFYrmlLg13J3xaG0dIxkinNi0Y6hA0I7jsBjiRRHtID4bYk9jgVph2jGi7ICB0oi+jY2x0Q0DnHLbPbuvYl9gW+BrUJ4i2mOE8gnQBjqJrkmM0lFc9UHl6DGBE0AoB2OBtPal43rOhHCQEhIpTUExIGZ2mv1VjPNbK4um7Wb8Irp8p6XkGvi2ly+arRkJVY4JTMsFF8LXEJwQbdptZbUNJIWwBZmzgla15h7xJRbx+kSea73GKYx9gSg4vdwj9juHu1lVCrMUrLgc3vs1KCxELoFXjNTps5DfNut6Bgxm63Lp4aO6dRm7GRkBcNQtmaHdfkCLTs5YWu1cV7cnRX5oYv6cAB9f869PUoQSnnORct4yiGXutcB8a9GiOBr58WdBT6gKYog2no8w8zW+s5LLjBbk5fdZefv3pNaw4dae6h3vvuM1uihVk6LzyGNH+qke8we0dGT9+Qc9L6yxptz9ZeDnbyvjtcLNNTP+V73H0aMQklAlwt9y+jZpVsqpWrvwjVkL54UF0Rgd5XvF/w+tVJRVs/4di0ca8qxB/1gNPYmvjvy42E4mkzC2ot+FMTeOIrc2B/74SQK43ojGoZeHPmuF/lDP479WIvtvcSFHmY1aEOEwmj7PA0A9NxxOJz4oReNh74Xe5NjPD13FMDlB/KRF4aTYBS0toIoHof+MI7C4RB2/cBuNTdlVX4BsBeP41EcRqNJFAVh4I97rc1oBO6PRwA+CoajY4A09mTiRcDYDzxgF7eBbQ9k+hYxvnt1cju9ztS06FVj5QcY41wo/QZwXHegSFHCnUTkIKnSW2joVEo7LfTPd4rzPIGxcXdfawlOb9dCD8oLJNYJdqKgh5o/4HivDe8GeJOY10JUfmqJEy7gduoLeEpU8nTzcAZNGUz5NgEoTkXhturjnK7B14JmWU7OUfuKQzKCE+RmK+FK8eJ09xwaRrK5RlvgK3jS9Xf12Ep4nj1Unw7a8Z5mdItodvnIixClOZYSdlZVns/pP9C9V9MBnD9Tzbl5c92A4zne62Mb/+qtFbquOx3A8nHN2hFQaVhOlb5rr+4dmqqEZ/uWQIvEyVpLsiNdGxMwOdMCCk8K+6Ba7EsipwOVndoaPDD2qPGrX0xBnWnbzaktAQUAOpAbkt4m/BNEMMMKw9uHZY2YQE3a2jTB/Doub/kOfSBrYifLE5xOJSD7Txzhqvi4PUK00nMk+lXMfyPQUMVzky8MynPw/xXa6rnZbwDjObi/gbeqbkj5TYo4aaz9jzq+0f+wDN6ztO5T8m36i2uzX0ALlieTBdat0dOeV/8C) (though note the precision caveats). We're also considering making the elevation accessible to custom shaders: https://github.com/CesiumGS/cesium/issues/9735.

**Comment by JordanMakesMaps** [comment]
@lilleyse okay, the `${POSITION_ABSOLUTE}` definitely makes more sense in my situation; my point clouds are large and using just the `${POSITION}` attribute seemed to based on the position of points in whichever tile was currently rendered (independently of the others). 

A few more questions if that's aright:

- LAS/LAZ files have the ability to store a set number of channels (x, y, z, intensity, NIR, classifications, etc.): by default does  Cesium retain these channels and store them in the tile when  uploading the LAS/LAZ files using the REST API? If so, can you point me to the documentation that describes how to access these attributes?
- I saw in some examples that there are attributes like `{Temperature}` and `{Height}`? I know these are not native to LAS/LAZ files so how are they being added to the tiles on Cesium? I'm assuming these are baked into the tiles using the Feature Table (as described in section 10.4 of the [reference card](https://github.com/CesiumGS/3d-tiles/blob/main/3d-tiles-reference-card.pdf)). Is that correct?

**Comment by lilleyse** [comment]
* Cesium ion automatically retains x, y, z, red, green, blue, intensity, and classification if they exist in the LAS/LAZ. In the future we may give finer grained control over this process and support other attributes.
* The tilesets with `Temperature` and `Height` were generated synthetically with https://github.com/CesiumGS/3d-tiles-validator/tree/main/samples-generator. If you want full control over which attributes go into the feature table you would need to tile the data yourself. We're hoping to provide more control over this in our tilers as well by supporting LAS 1.4 extended variable length records.
