### ISSUE TITLE
HELP:use experimental features,"KHR_techniques_webgl" is not working!

### ISSUE THREAD

**Issue by waterpeach** [CesiumGS/3d-tiles#612]
When setting ExperimentalFeatures.enableModelExperimental to true and uses the experimental features, the "KHR_techniques_webgl" extension is not working.But, When setting ExperimentalFeatures.enableModelExperimental to false, the "KHR_techniques_webgl" extension is 
right

**Comment by lilleyse** [comment]
Hi @waterpeach, that extension is not supported in the new experimental glTF implementation, and may soon be deprecated because it doesn't fit in well with the new architecture. We may try to find a different upgrade path for glTF 1.0 models. You can follow https://github.com/CesiumGS/cesium/issues/9520 for updates.
