### ISSUE TITLE
3D-Tiles 1.1 implicit tile : Octree

### ISSUE THREAD

**Issue by cjhdsg** [CesiumGS/3d-tiles#767]
Could you please provide a visual illustration of an octree partitioned using the Z-order curve (Morton order), similar to the way quadtrees are often depicted in the document?

Thank you for your assistance!

**Comment by javagl** [comment]
I don't have such an image handy right now. One could try to create such an image, but I'm not sure whether it would be helpful in the context of the specification itself. A [Google image search for 'morton order 3d'](https://www.google.com/search?tbm=isch&q=morton+order+3d) brings up a few images (that already show that it's hard to _visualize_ that). 

Beyond that, there are some common approaches for encoding/decoding these morton indices. You may want to have a look at the [implementation in CesiumJS](https://github.com/CesiumGS/cesium/blob/67bb8210898da16a92e321f04c185e1214538bd1/packages/engine/Source/Core/MortonOrder.js#L170), but there are other approaches. Since you mentioned that you are using C/C++: [`cesium-native`](https://github.com/CesiumGS/cesium-native/blob/bbe581bdbfc1705648195945ba946f6ae1bed821/Cesium3DTilesContent/src/ImplicitTilingUtilities.cpp#L74) is using the https://github.com/Forceflow/libmorton library for these computations.

**Comment by javagl** [comment]
I assume that there is no immediate action here. We could consider adding a visualization of the Morton order for octrees, but looking at the ambiguity of such a representation (as a 2D image), it would probably not add much value for the specification.
